modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
[[mods]]
modId="omnis_backpacks"
version="${file.jarVersion}"
displayName="Omnis Backpacks"
logoFile="icon.png"
credits='''The Minecraft Modding Discord and everyone there.
Its an amazing place full of a ton of amazing people, this mod wouldnt be possible without them.'''
authors="Sammy"
description='''
Omnis Backpacks is an addon to Omnis. It adds backpacks! (what a surprise!)
'''
[[dependencies.omnis_backpacks]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.5,)"
    ordering="NONE"
    side="BOTH"